### ISSUE TITLE
Logo e colori istituzionali

### ISSUE THREAD

**Issue by fabrizioeff** [Dinamosrl/Propezzano#15]
Ciao @ariesRC , appena possibile avrei bisogno del logo (vettoriale o psd in buona risoluzione) oltre ai codici colore per iniziare ad impostare il template.
Grazie

**Comment by ghost** [comment]
In allegato link download per scaricare file zip contenente fie vettoriale dei loghi e file testo con i codici colore.
http://we.tl/3htbJzNEOr
