### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by fabrizioeff** [Dinamosrl/Propezzano#16]
Appena possibile avrei bisogno delle font utilizzate nelle demo nei formati EOT - TTF - WOFF

**Comment by ghost** [comment]
La font è il Raleway, è su Google Font quindi penso che la puoi prendere direttamente dal sito senza problemi.
https://www.google.com/fonts/specimen/Raleway

**Comment by fabrizioeff** [comment]
grazie @ariesRC
