### ISSUE TITLE
Pagina contatti, come ci hai conosciuto?

### ISSUE THREAD

**Issue by buddies4sport** [Dinamosrl/Propezzano#19]
Va aggiunto al modulo per invio messaggi una tendina con i seguenti campi:

Social Network
Passaparola amici
Enoteca
Ricerca su internet
Recensione/Guida
Fiere

**Comment by fabrizioeff** [comment]
Per la pagina "contatti" ho creato due template:

variante 1 - in base alla grafica fornita
http://www.dinamosrl.it/adp/contatti/ 

variante 2 - unica colonna centrata
http://www.dinamosrl.it/adp/contatti-2/

attendo vs. feedback

**Comment by ghost** [comment]
Per quanto mi riguarda la pagina a colonna unica centrata funziona meglio rispetto a quello progettata.

**Comment by buddies4sport** [comment]
Anche per me meglio 1 colonna... solo che la tendina dovrebbe avere la stessa altezza dei campi del form

**Comment by fabrizioeff** [comment]
@buddies4sport mi fai uno screenshot di come lo vedi?

**Comment by buddies4sport** [comment]
![schermata 2015-06-08 alle 10 52 00](https://cloud.githubusercontent.com/assets/3440784/8031138/67c5b322-0dcc-11e5-97b9-25ce332dc91f.png)

**Comment by fabrizioeff** [comment]
ora la tendina dovresti vederla correttamente @buddies4sport . Se ok puoi chiudere la issue
