### ISSUE TITLE
Creare favicon con il logo del vino

### ISSUE THREAD

**Issue by buddies4sport** [Dinamosrl/Propezzano#22]
@ariesRC puoi per favore creare una favicon ed inviarla a @fabrizioeff ? Grazie

**Comment by ghost** [comment]
ecco la favicon
![favicon](https://cloud.githubusercontent.com/assets/12545579/8030767/d41479e4-0dc9-11e5-80b1-0ebe108e510a.png)

**Comment by fabrizioeff** [comment]
Inserita
