### ISSUE TITLE
Inserire i testi della pagina Abbazia

### ISSUE THREAD

**Issue by buddies4sport** [Dinamosrl/Propezzano#23]
Ecco i testi sia in italiano sia in inglese.

Secondo la leggenda il 10 maggio del 715 è la data di fondazione di una chiesa dedicata a Santa Maria Propiziatrice, menzionata in una bolla papale di Bonifacio IX (1389-1404). Non ci sono ad oggi prove documentali o archeologiche a suffragio di questo evento. Dall’anno 1000 circa esisteva una chiesa romanica a navata unica, con abside e una prima torre campanaria posta sul lato meridionale. Di quell’epoca sono ancora visibili le vestigia dell’abside all’interno della chiesa, l’oculo (riaperto in occasione del restauro del 1969-70) e il loggiato d’ingresso in facciata, e resti delle mura perimetrali all’esterno.

Quando i frati benedettini si insediarono nella struttura cominciarono dal 1285 a ingrandire la chiesa e a costruire il piano terra dell’abbazia. I lavori culminarono nel 1303 con la creazione del portale monumentale di Raimondo Dal Poggio, di scuola atriana, e nel 1371 (dalla data incisa sulla campana) con la fine dei lavori di costruzione del campanile, posto sul lato retro della chiesa secondo la regola benedettina, prima che l’ingresso principale fosse spostato nella posizione attuale, sul lato sud. Nel 1466 fu completato il coronamento della facciata e il portale venne spostato nella posizione attuale, mentre cominciava la costruzione del primo piano dell’abbazia e del pozzo con cisterna.

Nel 1580 il cardinale Ottavio Acquaviva donava il complesso ai frati osservanti. A partire dal 1597 iniziò ad essere dipinto il ciclo di affreschi, e dello stesso periodo la costruzione del corpo residenziale abbaziale, terminato nel 1650. Nel 1811 venne soppresso il convento dei frati minori osservanti, e il 1843 è l’ultimo anno di utilizzo della chiesa per le sepolture temporanee da parte del comune. Nel 1871 gli attuali proprietari acquistarono la proprietà e diedero inizio, nel 1940, ai primi lavori di restauro dell’abbazia e, nel 1969, della chiesa, donata alla diocesi, su direzione dell’architetto M. Moretti. Dal 2011 è cominciato un nuovo ciclo di lavori di restauro.

The 10th may of 715 is the legendary date of the foundation of a church dedicated to Santa Maria Propiziatrice (propitious), mentioned in a pontifical note by Pope Bonifacio IX (1389-1404). There are no documentary or archeological evidences about this fact.

We know that around 1000 a.d. there was a Romanesque church with one nave, apse and a little bell tower on the south side. Apse ruins in the church, the oculus (re-opened during the restoring works in 1969-70) and the entrance arcade on the façade, and part of the perimeter wall outside can still be recognized to this day.

When Benedictine friars began to settle the structure they started in 1285 to enlarge the church and to build the ground floor of the abbey. Work culminated in 1303 with the creation of the monumental portal by Raimondo Dal Poggio from Atri and in the 1371 (date engraved on the bell) with the end of the bell tower construction, placed on the backside of the church by the Benedictine rule, before they move the principal access on the south side. In 1466 they completed the crowning of the south façade and move the portal in the actual position, then began to build the first floor of the abbey and the well.

In 1580 cardinal Ottavio Acquaviva donated the complex to the observant friars. From 1597 the paint of the frescoes cycle started with the abbatial palace building, ended in 1650. In 1811 was suppressed the minor observant friars convent, and 1843 is the last year that the church was used for temporary burials by the municipality. In 1871 the actual owners bought the estate and started, in 1940, the first restoring works of the abbey and, in 1969, of the church, donated to the diocese, attended by architect M. Moretti. From 2011 has started the new restoring works.

**Comment by fabrizioeff** [comment]
Inseriti
