### ISSUE TITLE
Allineamento contenuti pagina contatti

### ISSUE THREAD

**Issue by buddies4sport** [Dinamosrl/Propezzano#24]
Va bene come detto la versione centrata, ma migliorerei l'allineamento dei contenuti nella parte bassa che sembrano non centrati.
![schermata 2015-06-08 alle 10 29 11](https://cloud.githubusercontent.com/assets/3440784/8030742/9d9e01aa-0dc9-11e5-800b-f085a08fb525.png)

**Comment by fabrizioeff** [comment]
@buddies4sport modificato allineamento. Dammi feedback e se ok puoi chiudere

**Comment by buddies4sport** [comment]
:+1:
