### ISSUE TITLE
Texture del footer

### ISSUE THREAD

**Issue by buddies4sport** [Dinamosrl/Propezzano#26]
@ariesRC @fabrizioeff cercherei di rendere più sfumata la differenza di grigi nel footer in modo da far spiccare meno la trama del logo e migliorare la leggibilità del testo. Credo sia meglio rendere lo sfondo chiaro un po' più scuro e quindi vicino al grigio del logo.

![schermata 2015-06-08 alle 10 36 18](https://cloud.githubusercontent.com/assets/3440784/8030845/7626cf0c-0dca-11e5-9aa8-b8e889a12450.png)

**Comment by ghost** [comment]
@buddies4sport se così va bene @fabrizioeff può procedere con la modifica...il codice colore è 868585
![schermata 2015-06-08 alle 10 58 40](https://cloud.githubusercontent.com/assets/12545579/8031296/8a8c9fdc-0dcd-11e5-825d-76397a13ec2f.png)

**Comment by buddies4sport** [comment]
Si meglio, possiamo procedere

**Comment by fabrizioeff** [comment]
Aggiornato pattern footer
