### ISSUE TITLE
Allineamento contenuti home page

### ISSUE THREAD

**Issue by buddies4sport** [Dinamosrl/Propezzano#28]
In home page le tre bottiglie delle categorie non sono allineate al centro della pagina

**Comment by buddies4sport** [comment]
![schermata 2015-06-09 alle 10 50 26](https://cloud.githubusercontent.com/assets/3440784/8054008/9c8ce598-0e95-11e5-93b2-5322df6bef08.png)

**Comment by fabrizioeff** [comment]
@buddies4sport anche qui dovrebbe essere ok.

**Comment by buddies4sport** [comment]
:+1:
