### ISSUE TITLE
Modifica bandierine scelta lingua

### ISSUE THREAD

**Issue by ghost** [Dinamosrl/Propezzano#29]
In accordo con @buddies4sport è stato deciso di modificare le icone delle bandiere poichè "sbattono" un po con il resto della grafica. Se è possibile vanno modificate con queste.

![eng](https://cloud.githubusercontent.com/assets/12545579/8057810/e6ba1716-0eb4-11e5-8864-381f543f7fc6.png)
![ita](https://cloud.githubusercontent.com/assets/12545579/8057813/ea71b0ee-0eb4-11e5-9013-5a4f68e1ec1d.png)

**Comment by fabrizioeff** [comment]
Cambiate!
