### ISSUE TITLE
Ridimensionamento menù doppio

### ISSUE THREAD

**Issue by ghost** [Dinamosrl/Propezzano#30]
La parte superiore del menù, quindi quella con le tre Linee di vino, va fatta più fina.

![schermata 2015-06-10 alle 08 35 54](https://cloud.githubusercontent.com/assets/12545579/8076364/e033ea60-0f4b-11e5-8046-40c6f4be6b67.png)

**Comment by fabrizioeff** [comment]
diminuita l'altezza. Se ok puoi chiudere la issue @ariesRC
