### ISSUE TITLE
Costruire il template dell'home page

### ISSUE THREAD

**Issue by buddies4sport** [Dinamosrl/Propezzano#6]
Ovviamente questa può essere svolta solo dopo la chiusura della #2

**Comment by fabrizioeff** [comment]
Il template della Home Page è pronto, attendo vs. feedback
http://www.dinamosrl.it/adp/

**Comment by buddies4sport** [comment]
Mi sembra ok... 
@ariesRC che dici possiamo provare a recuperare un po' di spazio tra la riga rossa e le bottiglie? 
@fabrizioeff l'immagine in alto è pronta per essere uno slider con più immagini? (se ne metteranno 3) pensavo ad un passaggio ogni 5 secondi...

**Comment by ghost** [comment]
@buddies4sport penso che non ci siano problemi se tiriamo su un po tutto il contenuto della pagina.

**Comment by fabrizioeff** [comment]
@buddies4sport si lo slider è pronto per inserire quante immagini vogliamo. Inviatemi le definitive e le carico subito.
Ok anche per la linea rossa, riduco lo spazio.

**Comment by buddies4sport** [comment]
ok ottimo.. allora se alziamo un po' le bottiglie in modo che lo spazio tra le bottiglie e la riga sia uguale a quello che c'è tra l'immagine e la riga siamo a posto. @fabrizioeff poi compaiono dei pallini in basso per selezionare una delle foto o per farle scorrere manualmente?

**Comment by fabrizioeff** [comment]
@buddies4sport ti ho fatto un esempio in Home Page. Possiamo inserire frecce e pallini o escludere uno dei due. Se decidessimo di eliminare le frecce rimane comunque la funzione "Swipe" sia su Desktop che sui vari supporti mobile.

**Comment by buddies4sport** [comment]
lasciamo tutte e due le funzionalità attive. chiudo
