### ISSUE TITLE
Definizione grafica pagina Vini

### ISSUE THREAD

**Issue by buddies4sport** [Dinamosrl/Propezzano#9]
Al momento è questa, in attesa di revisioni:

![vini](https://cloud.githubusercontent.com/assets/3440784/7798319/c74d2fe8-02f8-11e5-9954-ddd8d335c338.jpg)

**Comment by fabrizioeff** [comment]
Creata la pagina "vini" secondo le grafiche definitive fornite nella #20 
http://www.dinamosrl.it/adp/vini/

**Comment by ghost** [comment]
Bene così. 

Unica cosa che però riguarda tutto il sito è la font. Non sono sicura sia quella usata nella grafica.

**Comment by fabrizioeff** [comment]
Totalmente d'accordo con te, anche io faccio fatica a leggere con questa font. La famiglia di caratteri utilizzata è la stessa che mi avete indicato.

Il problema credo dipenda dal browser su cui si visualizza il sito, nel mio caso su Chrome è illeggibile, ma su Firefox va bene (a parte difetti di font-weight che verranno aggiustati con specifici Hacks in seguito)

**Comment by buddies4sport** [comment]
Credo che possiamo usare qualsiasi font classica per siti. L'importante è che sia ben leggibile e non dia problemi... a voi la scelta

**Comment by fabrizioeff** [comment]
Ho cambiato la font Ralway con Open Sans. Fatemi sapere se ok

**Comment by buddies4sport** [comment]
font ok
